import type { Course } from "./types";

/**
 * Recovered from the legacy Adobe Express course pages. Generated by
 * scripts/build_courses_from_adobe.py - course copy preserved verbatim.
 */
export const perfectSelfTapeCourse: Course = {
  "slug": "perfect-self-tape",
  "title": "The Perfect Self Tape",
  "subtitle": "A Parent Course",
  "description": "The recovered Child Actor 101 self tape course for parents. Ten sections covering equipment, lighting, framing, slates, readers, performance coaching, editing, parent survival, sending tapes, and when to bend the rules - migrated from the original course with every lesson, video position, and resource preserved.",
  "legacyAdobeUrl": "https://express.adobe.com/page/4N3CH5BgyUPgp/",
  "sections": [
    {
      "slug": "equipment",
      "title": "Essential Equipment",
      "legacyAdobeUrl": "https://express.adobe.com/page/t89Ol45aZnWWO/"
    },
    {
      "slug": "properly-lit",
      "title": "Properly Lit: Self Tape Lighting Explained",
      "legacyAdobeUrl": "https://express.adobe.com/page/fKEcYmY4tk1Ru/"
    },
    {
      "slug": "perfect-frame",
      "title": "The Perfect Frame",
      "legacyAdobeUrl": "https://express.adobe.com/page/5HkJaHOKEnWA5/"
    },
    {
      "slug": "slates",
      "title": "Slates That Pop",
      "legacyAdobeUrl": "https://express.adobe.com/page/HTdXKtkSq3Ksq/"
    },
    {
      "slug": "role-of-the-reader",
      "title": "The Role of the Reader",
      "legacyAdobeUrl": "https://express.adobe.com/page/9h9pR9OX1OZq7/"
    },
    {
      "slug": "coaching",
      "title": "Performance Coaching",
      "legacyAdobeUrl": "https://express.adobe.com/page/FrbVFiuNM7Jxy/"
    },
    {
      "slug": "quick-editing",
      "title": "Quick Editing",
      "legacyAdobeUrl": "https://express.adobe.com/page/OQdMObzEI8etD/"
    },
    {
      "slug": "parent-survival",
      "title": "Parent Survival Tips",
      "legacyAdobeUrl": "https://express.adobe.com/page/ZYQXknWCAzt3i/"
    },
    {
      "slug": "sending-tapes",
      "title": "Sending Your Tapes",
      "legacyAdobeUrl": "https://express.adobe.com/page/E3kmokZywrFef/"
    },
    {
      "slug": "bending-the-rules",
      "title": "Bending the Rules",
      "legacyAdobeUrl": "https://express.adobe.com/page/ko5JZe1bqtBnz/"
    }
  ],
  "lessons": [
    {
      "slug": "essential-lighting-softboxes",
      "title": "Lighting Gear: Softboxes & the 3-Point Setup",
      "sectionSlug": "equipment",
      "body": [
        {
          "heading": "While you can surprisingly find a lot of items around your home to make-shift a Self Tape on the fly. It is wise to invest in some Essential Equipment that you can rely on to assist in producing great, professional looking self tapes. This gear will make the Actor look good, sound great and should pop out to a Casting Director.",
          "paragraphs": [
            "And it doesn't have to cost you a small fortune! For under $150 you can get an arsenal of necessities in Self Tape Gear. At the end of this section there is a shopping guide with links to some of the best prices on Amazon for items mentioned."
          ]
        },
        {
          "heading": "Video Recording Device / It is up to you which route you want to take in capturing video. Do not feel like you have to use a prosumer DSLR camera if that is not in the budget.",
          "paragraphs": [
            "Superb Self Tapes are sent out everyday using Smartphones and Tablets. Most newer models record at a quality so high that isn’t even necessary for a Self Tape.",
            "720p will deliver exceptional looking results"
          ]
        },
        {
          "heading": "Great Lighting is Essential in producing a quality Self Tape. / A Simple 3-Point Lighting Set Up will do wonders for your Self Tapes. / The Strongest Light will be the Main Light.",
          "paragraphs": [
            "This Main Light will be 45% from the lens of your recording device. To the right or left."
          ]
        },
        {
          "heading": "The second brightest will be your Fill Light.",
          "paragraphs": [
            "A Fill Light is used to eliminate shadows on the face. This light will be powered to about 60% intensity and angled towards subject on the other side of the lens."
          ]
        },
        {
          "heading": "The third light...",
          "paragraphs": [
            "A Hair Light or Backlight is often overlooked. This light will be used to separate the subject from the backdrop and really make you look like a professional. It creates depth and makes the Actor pop.",
            "This light will be low intensity around 30%. And it will be fixed above or behind the subject."
          ]
        },
        {
          "heading": "Softboxes are the trusty standard in Video Lighting. They produce a soft filtered light. This light is even and pleasing to skin tones.",
          "paragraphs": [
            "Softboxes are relatively inexpensive and very lightweight.",
            "They come in Square, Rectangle and Octagon Shapes.",
            "Most commonly for Self Tapes a 20\" - 28\" rectangle softbox is used."
          ]
        }
      ],
      "resources": [
        {
          "title": "Softbox Article",
          "href": "https://www.karltayloreducation.com/lighting-modifiers-softboxes/"
        }
      ],
      "legacyAdobeUrl": "https://express.adobe.com/page/t89Ol45aZnWWO/",
      "summary": "And it doesn't have to cost you a small fortune! For under $150 you can get an arsenal of necessities in Self Tape Gear. At the end of this section there is...",
      "video": {
        "kind": "youtube",
        "videoId": "Oum3SuOsAN4",
        "thirdParty": true,
        "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
      }
    },
    {
      "slug": "ring-lights",
      "title": "Ring Lights",
      "sectionSlug": "equipment",
      "body": [
        {
          "heading": "Ring Light / Ring Lights have increased in popularity the last few years. Consumer Ring Light production has given affordable options to those wanting the beauty enhancing qualities of light.",
          "paragraphs": [
            "Ring Lights come in sizes from 6\" to 24\" or above. Most common for Self Tapes is a 18\" Ring Light.",
            "Ring Lights are Bi-Color meaning they can adjust from Warm Light to Cool Light. They also have variable intensity of brightness."
          ]
        },
        {
          "heading": "Ring Lights are best used for your MAIN LIGHT.",
          "paragraphs": []
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/t89Ol45aZnWWO/",
      "summary": "Ring Lights come in sizes from 6\" to 24\" or above. Most common for Self Tapes is a 18\" Ring Light.",
      "video": {
        "kind": "youtube",
        "videoId": "K4wsrW0VpLE",
        "thirdParty": true,
        "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
      }
    },
    {
      "slug": "led-lights",
      "title": "LED Lights",
      "sectionSlug": "equipment",
      "body": [
        {
          "heading": "LED / Video production loves the use of LED lights because they are low energy and last several times longer than traditional light bulbs.",
          "paragraphs": [
            "Flat Panel LED Light"
          ]
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/t89Ol45aZnWWO/",
      "summary": "Flat Panel LED Light",
      "videos": [
        {
          "kind": "youtube",
          "videoId": "TiAsjx5j7GA",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        },
        {
          "kind": "youtube",
          "videoId": "B00GMcqSWjk",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        }
      ]
    },
    {
      "slug": "tripods-and-audio",
      "title": "Tripods, Mounts & Lavalier Mics",
      "sectionSlug": "equipment",
      "body": [
        {
          "heading": "Keeping your video from shaking is the easiest and first step to creating a quality Self Tape. / You need a Tripod!",
          "paragraphs": [
            "A standard tripod between 50\" and 70\" is ideal for Self Tape Videos"
          ]
        },
        {
          "heading": "You will need separate mounts for your tripod if you are using a Tablet or Smartphone as your recording device.",
          "paragraphs": [
            "Tablet Mount",
            "Smartphone Mount"
          ]
        },
        {
          "heading": "Bad sound is the number one killer of amateur video. / A Microphone is an easy fix to many Self Tape Woes. / A Lavalier or \"Lapel\" Mic is easily adaptable to use with Smartphones, Cameras and Tablets.",
          "paragraphs": [
            "They come with long enough cords to not be confining.",
            "The lapel mic will focus the sound on the Actor and lessen the volume from The Reader, who is usually operating the camera."
          ]
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/t89Ol45aZnWWO/",
      "summary": "A standard tripod between 50\" and 70\" is ideal for Self Tape Videos",
      "video": {
        "kind": "youtube",
        "videoId": "hoj_uDLJpm4",
        "thirdParty": true,
        "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
      }
    },
    {
      "slug": "backdrops-and-shopping-list",
      "title": "Backdrops & the Shopping Guide",
      "sectionSlug": "equipment",
      "body": [
        {
          "paragraphs": [
            "Since Lapel mics have a 3.5mm Audio connection. You will most likely need an adapter to use it with an Iphone or Ipad.",
            "They make simple adapters for Lightning and C-Type"
          ]
        },
        {
          "heading": "BACKDROPS / It is perfectly acceptable to use a plain wall in your home or even an Unwrinkled sheet. / You will find the Self Tapes that look really polished have a backdrop that compliments the Actor in a pleasing color. / Shades of Grey, Blue, Green, Brown are popular choices. / Popup shades are easily transportable and create a Self Tape studio wherever you are. / Our go-to backdrop is a Grey Wool blanket that adds texture and does not reflect hot light.",
          "paragraphs": [
            "As an Amazon Associate I earn from qualifying purchases."
          ]
        }
      ],
      "resources": [
        {
          "title": "Two Softbox Kit $42.99",
          "href": "https://amzn.to/38HsN4u"
        },
        {
          "title": "Three Rectangle Softbox Kit $66.99",
          "href": "https://amzn.to/326sMVr"
        },
        {
          "title": "Three Octagon Softbox Kit $69.99",
          "href": "https://amzn.to/327GYgH"
        },
        {
          "title": "18\" Ring Light Kit $68.99",
          "href": "https://amzn.to/38GGvoo"
        },
        {
          "title": "14\" Ring Light $47.80",
          "href": "https://amzn.to/326rz0l"
        },
        {
          "title": "12\" Ring Light $35.99",
          "href": "https://amzn.to/37HotAS"
        },
        {
          "title": "10\" LED Multi-Color Ring Light $42.99",
          "href": "https://amzn.to/326sMVr"
        },
        {
          "title": "LED Panel $57.99",
          "href": "https://amzn.to/2V5YaSf"
        },
        {
          "title": "Two Light Stands $25.99",
          "href": "https://amzn.to/2uVYPuU"
        },
        {
          "title": "55\" Tripod $14.99",
          "href": "https://amzn.to/39IFkF5"
        },
        {
          "title": "60\" Tripod $23.99",
          "href": "https://amzn.to/2SDRjxO"
        },
        {
          "title": "Tablet Tripod Adapter $13.99",
          "href": "https://amzn.to/2T17h42"
        },
        {
          "title": "Smartphone Tripod Mount $6.89",
          "href": "https://amzn.to/38DZX5e"
        },
        {
          "title": "Lapel Microphone $11.99",
          "href": "https://amzn.to/2SFXwtm"
        },
        {
          "title": "Apple USB-C to Headphone Jack $7.99",
          "href": "https://amzn.to/38JKEYw"
        },
        {
          "title": "Apple Headphone Lightning Adapter $7.99",
          "href": "https://amzn.to/2P8hPNT"
        },
        {
          "title": "Grey Wool Blanket $16.01",
          "href": "https://amzn.to/2P8ksiB"
        },
        {
          "title": "Backdrop Stand $30.99",
          "href": "https://amzn.to/39FXhE6"
        },
        {
          "title": "Pop Up Backdrop $55.95",
          "href": "https://amzn.to/37HhtUN"
        },
        {
          "title": "Grey Textured Backdrop $17.90",
          "href": "https://amzn.to/2HAycyD"
        },
        {
          "title": "Blue Textured Backdrop $15.88",
          "href": "https://amzn.to/2ubvNat"
        },
        {
          "title": "Yellow Backdrop $11.68",
          "href": "https://amzn.to/3bPL4yM"
        },
        {
          "title": "Photo Clamps $7.99",
          "href": "https://amzn.to/2ua0iNS"
        }
      ],
      "legacyAdobeUrl": "https://express.adobe.com/page/t89Ol45aZnWWO/",
      "summary": "Since Lapel mics have a 3.5mm Audio connection. You will most likely need an adapter to use it with an Iphone or Ipad."
    },
    {
      "slug": "understanding-lighting",
      "title": "Understanding Lighting",
      "sectionSlug": "properly-lit",
      "body": [
        {
          "paragraphs": [
            "There is no image without light"
          ]
        },
        {
          "heading": "Even a good performance can be overshadowed",
          "paragraphs": [
            "Shadows. Can’t see eyes. Too much space above head.",
            "Orange light. Bad Framing. Shadows on Wall.",
            "Hot spots of light. Bad Frame. Dark background sucks light.",
            "Green screen backdrop. Shadows. No Depth."
          ]
        },
        {
          "heading": "Getting it Right - Sets You Apart / Understanding Lighting",
          "paragraphs": []
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/fKEcYmY4tk1Ru/",
      "summary": "There is no image without light",
      "video": {
        "kind": "youtube",
        "videoId": "nqMQZG68Wkc",
        "thirdParty": true,
        "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
      }
    },
    {
      "slug": "lighting-gear",
      "title": "Make Sure You Have the Gear",
      "sectionSlug": "properly-lit",
      "body": [
        {
          "heading": "First let’s make sure you got the gear",
          "paragraphs": []
        }
      ],
      "resources": [
        {
          "title": "Soft Boxes And How They Work",
          "href": "https://www.karltayloreducation.com/lighting-modifiers-softboxes/"
        },
        {
          "title": "About LED In Video Shooting",
          "href": "https://www.diyphotography.net/ten-tips-read-buy-led-lights-video/"
        }
      ],
      "legacyAdobeUrl": "https://express.adobe.com/page/fKEcYmY4tk1Ru/",
      "videos": [
        {
          "kind": "youtube",
          "videoId": "gj3R0OM2mKc",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        },
        {
          "kind": "youtube",
          "videoId": "qSTGnl7HHao",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        }
      ]
    },
    {
      "slug": "learning-to-light",
      "title": "Learning to Light",
      "sectionSlug": "properly-lit",
      "body": [
        {
          "heading": "Learning to Light",
          "paragraphs": []
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/fKEcYmY4tk1Ru/",
      "videos": [
        {
          "kind": "youtube",
          "videoId": "rq0q3Ea5fkQ",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        },
        {
          "kind": "youtube",
          "videoId": "j_Sov3xmgwg",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        },
        {
          "kind": "youtube",
          "videoId": "xJAI7ddS-b0",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        }
      ]
    },
    {
      "slug": "a-real-home-setup",
      "title": "A Real Home Self Tape Setup",
      "sectionSlug": "properly-lit",
      "body": [
        {
          "heading": "Lexi Janicek’s Mother explains her home setup / Laura Janiceck uses three lights in her home self tape setup of Lexi. / She places Lexi THREE FEET from Camera and FOUR FEET from Backdrop. / She uses TWO 24” Softboxes in front of Lexi as her MAIN and FILL LIGHTS. / LED Hair Light",
          "paragraphs": [
            "I have the middle of the soft boxes hitting at her eye level... the hair light is not on a boom, but the light that I use is able to angle down. I have it angling about 45 degrees in relation to the stand."
          ]
        },
        {
          "heading": "Hair Light/Kicker Light/Back Light / Soft Box on Boom Stand / Round LED Panel / 8 by 36 inch Softbox / 10 inch Ring Light / LED Flat Panel / LED Flat Panel on Stand",
          "paragraphs": []
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/fKEcYmY4tk1Ru/",
      "summary": "I have the middle of the soft boxes hitting at her eye level... the hair light is not on a boom, but the light that I use is able to angle down. I have it an...",
      "videos": [
        {
          "kind": "youtube",
          "videoId": "uCAnQ8gipcg",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        },
        {
          "kind": "youtube",
          "videoId": "9NWAcK-wM80",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        }
      ]
    },
    {
      "slug": "skin-tones-and-mood",
      "title": "Skin Tones & Mood",
      "sectionSlug": "properly-lit",
      "body": [
        {
          "heading": "Skin tones should not be overlooked",
          "paragraphs": []
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/fKEcYmY4tk1Ru/",
      "video": {
        "kind": "youtube",
        "videoId": "QhVOLaRHv94",
        "thirdParty": true,
        "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
      }
    },
    {
      "slug": "the-perfect-frame",
      "title": "The Perfect Frame",
      "sectionSlug": "perfect-frame",
      "body": [
        {
          "paragraphs": [
            "Letterbox"
          ]
        },
        {
          "heading": "No / YES",
          "paragraphs": []
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/5HkJaHOKEnWA5/",
      "summary": "Letterbox",
      "needsReview": true,
      "reviewNote": "The legacy page was visual-only (good vs. bad frame comparison images hosted by Adobe; not migrated). No video embed existed on the page. Candidate Bunny video 694fccfe-955e-4cff-90da-91d7e479f423 ('Self Tape Framing - Entrances.mp4', main library) may belong here - unconfirmed."
    },
    {
      "slug": "slates-that-pop",
      "title": "Bonus Slate Shot Ideas",
      "sectionSlug": "slates",
      "body": [
        {
          "heading": "A Slate should be filmed separately from the audition sides.",
          "paragraphs": [
            "Repeating slate over and over before a scene reading pulls an Actor out of Scene preparation and Character."
          ]
        },
        {
          "heading": "In a Self Tape the Slate is the one opportunity an Actor has to show their charisma and vibe with the Casting Director.",
          "paragraphs": [
            "In the Casting Room, conversation and personal interaction is a Huge component in a potential callback"
          ]
        },
        {
          "heading": "You must use the Slate as your one opportunity to have them see who you are and why they should want to get to know you",
          "paragraphs": [
            "Don’t be afraid to stand out. Adding a few seconds of personality never hurt anybody.",
            "Always use Specific Slate Instructions if Casting provides"
          ]
        },
        {
          "heading": "Bonus Slate Shot Ideas",
          "paragraphs": []
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/HTdXKtkSq3Ksq/",
      "summary": "Repeating slate over and over before a scene reading pulls an Actor out of Scene preparation and Character.",
      "video": {
        "kind": "bunny",
        "guid": "d75ef465-5688-4d80-8ea2-59c595e44df3",
        "title": "What is a Slate Shot-",
        "needsReview": true,
        "note": "Mapped from legacy Vimeo embed with medium confidence. Verify this is the intended lesson video."
      },
      "needsReview": true,
      "reviewNote": "One or more videos in this lesson are unverified or awaiting a replacement."
    },
    {
      "slug": "the-reader-parent-course",
      "title": "The Reader (Live Parent Course)",
      "sectionSlug": "role-of-the-reader",
      "body": [
        {
          "heading": "Sides - Pages from a Script that is chosen for an Actor to Audition with for a particular role. / Teaching cements Learning! / MEGA TIP",
          "paragraphs": [
            "Be half the volume of the actor as the reader!"
          ]
        },
        {
          "heading": "Excerpts from a LIVE Parent Course called \"The Reader\"",
          "paragraphs": []
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/9h9pR9OX1OZq7/",
      "summary": "Be half the volume of the actor as the reader!",
      "video": {
        "kind": "bunny",
        "guid": "ca3cb3c4-aea2-455c-8b26-490b28013684",
        "title": "The role of the reader - Parent Self Tape course for Child Actor 101",
        "note": "Bunny copy is the full 69-minute parent-course session; the legacy page described 'excerpts'."
      }
    },
    {
      "slug": "coaching-the-opportunity",
      "title": "Coaching the Opportunity",
      "sectionSlug": "coaching",
      "body": [
        {
          "heading": "Acting styles vary by Genre... / A scene is way more than just dialogue!",
          "paragraphs": [
            "Casting Talks Auditions"
          ]
        }
      ],
      "resources": [
        {
          "title": "Get PDF on Content Memorization",
          "href": "https://www.parentsofactors.xyz/fast-sides-memorization"
        },
        {
          "title": "Make Bold Choices",
          "href": "https://www.castittalent.com/blog/2015/03/bold-choices-make-them-remember-you/"
        }
      ],
      "legacyAdobeUrl": "https://express.adobe.com/page/FrbVFiuNM7Jxy/",
      "summary": "Casting Talks Auditions",
      "video": {
        "kind": "bunny",
        "guid": "435006c3-5890-4e01-8b65-81ad43b099d6",
        "title": "Parent Coaching Tips",
        "needsReview": true,
        "note": "Mapped from legacy Vimeo embed with medium confidence. Verify this is the intended lesson video."
      },
      "needsReview": true,
      "reviewNote": "One or more videos in this lesson are unverified or awaiting a replacement."
    },
    {
      "slug": "trimming-videos",
      "title": "Trimming Videos Quickly",
      "sectionSlug": "quick-editing",
      "body": [],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/OQdMObzEI8etD/",
      "video": {
        "kind": "youtube",
        "videoId": "ci0ivwWQ6vQ",
        "thirdParty": true,
        "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
      }
    },
    {
      "slug": "merging-and-sound",
      "title": "Merging & Sound on iPad",
      "sectionSlug": "quick-editing",
      "body": [],
      "resources": [
        {
          "title": "Merge On IPad",
          "href": "https://www.lifewire.com/how-to-edit-video-ipad-4045025"
        }
      ],
      "legacyAdobeUrl": "https://express.adobe.com/page/OQdMObzEI8etD/",
      "video": {
        "kind": "youtube",
        "videoId": "VJOnSgoTcT8",
        "thirdParty": true,
        "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
      }
    },
    {
      "slug": "coreys-editing-walkthrough",
      "title": "Corey's App Overview & Edit Walkthrough",
      "sectionSlug": "quick-editing",
      "body": [],
      "resources": [
        {
          "title": "VideoSoap Great App For Sound",
          "href": "http://www.soundness-llc.com/products/videosoap5/"
        }
      ],
      "legacyAdobeUrl": "https://express.adobe.com/page/OQdMObzEI8etD/",
      "videos": [
        {
          "kind": "missing",
          "legacyVimeoId": "391760430",
          "note": "Corey's Enlight (Videoleap) app overview. Also embedded on Perfect Self Tape 'Quick Editing'.",
          "candidates": [
            "f5b0854e-6c52-44f3-ae0d-ab13c364d774 - Untitled (5).mp4",
            "a855464e-d499-4221-98fa-dd884df2146d - Untitled (6).mp4",
            "1067ad2b-49aa-48e6-a4ed-cc533e61ec07 - Videoleap-459739BD export.mp4 (main library)"
          ]
        },
        {
          "kind": "bunny",
          "guid": "e2c4531b-5651-423e-bdc4-4a5866104e10",
          "title": "Walk through an Edit"
        }
      ],
      "needsReview": true,
      "reviewNote": "One or more videos in this lesson are unverified or awaiting a replacement."
    },
    {
      "slug": "all-in-one-apps",
      "title": "All-in-One Apps",
      "sectionSlug": "quick-editing",
      "body": [
        {
          "heading": "All In One Apps",
          "paragraphs": []
        }
      ],
      "resources": [
        {
          "title": "Slatable App",
          "href": "https://www.google.com/url?sa=t&source=web&cd=1&ved=2ahUKEwjYm_W-7vnnAhXJv54KHRveAdsQFjAAegQIAhAB&url=https%3A%2F%2Fwww.slatable.com%2F&usg=AOvVaw319KU3x6cJO6MUJNM0qYwO"
        },
        {
          "title": "My Self Tape App",
          "href": "https://www.myselftapeapp.com/"
        },
        {
          "title": "Shoot Me App",
          "href": "https://www.shoot.me/"
        }
      ],
      "legacyAdobeUrl": "https://express.adobe.com/page/OQdMObzEI8etD/",
      "videos": [
        {
          "kind": "youtube",
          "videoId": "cSmb2_zBFs4",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        },
        {
          "kind": "youtube",
          "videoId": "YxIpZR1Vy1Q",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        }
      ]
    },
    {
      "slug": "stress-free-taping",
      "title": "Survival Tips: Stress-Free Taping",
      "sectionSlug": "parent-survival",
      "body": [
        {
          "heading": "A Favorite Interview on Self Tapes",
          "paragraphs": []
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/ZYQXknWCAzt3i/",
      "video": {
        "kind": "youtube",
        "videoId": "7htgIHQikMI",
        "thirdParty": true,
        "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
      }
    },
    {
      "slug": "file-formats-and-compression",
      "title": "File Formats & Compression",
      "sectionSlug": "sending-tapes",
      "body": [
        {
          "paragraphs": [
            "Check the extension of your video file to see if it an .mp4 or .mov If it is not either you will want to use a file converter app or software to make sure it is a compatible video file that everyone can view with ease.",
            "BIGGER IS NOT ALWAYS BETTER",
            "Nobody likes HUGE attachments!"
          ]
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/E3kmokZywrFef/",
      "summary": "Check the extension of your video file to see if it an .mp4 or .mov If it is not either you will want to use a file converter app or software to make sure it...",
      "video": {
        "kind": "youtube",
        "videoId": "z_VtxrKolZU",
        "thirdParty": true,
        "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
      }
    },
    {
      "slug": "handbrake",
      "title": "Compressing with Handbrake",
      "sectionSlug": "sending-tapes",
      "body": [
        {
          "heading": "Android Users / Quality, Easy and Free / iOS Users / Easy presets to shrink. / Desktop/Laptop (MAC & Windows) / Free. Open Source. Amazing Results. No quality loss in reduction.",
          "paragraphs": []
        }
      ],
      "resources": [
        {
          "title": "VidCompact For Android",
          "href": "https://play.google.com/store/apps/details?id=com.xvideostudio.videocompress"
        },
        {
          "title": "Video Compress - iOS Apple",
          "href": "https://apps.apple.com/app/video-compress-shrink-vids/id997699744"
        }
      ],
      "legacyAdobeUrl": "https://express.adobe.com/page/E3kmokZywrFef/",
      "video": {
        "kind": "youtube",
        "videoId": "j4xs37QFDE8",
        "thirdParty": true,
        "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
      }
    },
    {
      "slug": "uploading-to-ecocast",
      "title": "Uploading to EcoCast (Actors Access)",
      "sectionSlug": "sending-tapes",
      "body": [
        {
          "heading": "My Favorite is WeTransfer / It’s free, fast and you get notifications once party downloads. / Giving you peace of mind. / Uploading to EcoCast via Actors Access / Eco Cast® is a \"virtual pre-read system\" provided by Breakdown Services. With it, Casting Directors can send invitations to Talent Representatives or Actors directly to record an audition themselves, expanding the range of people Casting Directors can see for each role.",
          "paragraphs": []
        }
      ],
      "resources": [
        {
          "title": "How to Use Handbrake",
          "href": "https://www.imore.com/how-compress-video-handbrake"
        },
        {
          "title": "Download Handbrake - FREE",
          "href": "https://handbrake.fr"
        },
        {
          "title": "EcoCast Tutorial",
          "href": "https://actorsaccess.freshdesk.com/support/solutions/articles/17000056214-how"
        }
      ],
      "legacyAdobeUrl": "https://express.adobe.com/page/E3kmokZywrFef/",
      "videos": [
        {
          "kind": "youtube",
          "videoId": "2c5bGtJJt4o",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        },
        {
          "kind": "youtube",
          "videoId": "TMGcgzR4le8",
          "thirdParty": true,
          "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
        }
      ]
    },
    {
      "slug": "security-and-final-tips",
      "title": "Security, Two Takes & the Clock",
      "sectionSlug": "sending-tapes",
      "body": [
        {
          "heading": "You cannot have private enough security measures for some NDA projects / Use Vimeo Instead / Better security. Trusted in Industry. / Feel free and encouraged to send TWO TAKES of each scene to display an ALTERNATE CHOICE.",
          "paragraphs": [
            "Reps have a trained eye to see what needs strengthening and have a better idea of what Casting is looking for. If they are able to review your self tape then they are getting a glimpse into what the actor's audition is like and this can be very helpful."
          ]
        },
        {
          "heading": "Keep your EYE on the CLOCK!",
          "paragraphs": []
        }
      ],
      "resources": [
        {
          "title": "Vimeo",
          "href": "http://vimeo.com"
        }
      ],
      "legacyAdobeUrl": "https://express.adobe.com/page/E3kmokZywrFef/",
      "summary": "Reps have a trained eye to see what needs strengthening and have a better idea of what Casting is looking for. If they are able to review your self tape then..."
    },
    {
      "slug": "setting-the-mood-with-music",
      "title": "Setting the Mood: Music & Underscore",
      "sectionSlug": "bending-the-rules",
      "body": [
        {
          "heading": "There is always a \"Gray Area\" / And for every Industry Standard there are 100 caveats",
          "paragraphs": [
            "If you are going to “Break a Rule”..."
          ]
        },
        {
          "heading": "My advice is to make it count and the project should be worth it! / This is a major rule that should almost never be broken. / Most people do not have the skill to film a scene environmentally would look good enough to make an impact and not hurt a performance. / Using another Actor on screen with the auditioning Actor is very frowned upon. It can hurt a performance if the other Actor is bad or not the appropriate type for role. / Even an arm or hand from an off-screen reader can be distracting and look Amateurish. / BUT... / On occasion it has been a worthy gamble. / A challenging scene with a lot of Action can come to life when taken out if the confinements of a Self Tape Frame.",
          "paragraphs": [
            "Running from a bad guy.",
            "Having a Physical Altercation."
          ]
        },
        {
          "heading": "A better performance may need some reality infused to really showcase the right emotions or reactions. / Self Tapes do not need music or sound effects to be effective. Casting is looking at the Actor’s performance. / But there are times when an Actor can get into mood by hearing some underscore or music that would be played in the environment of the scene.",
          "paragraphs": [
            "In fact, a great coaching technique I use is listening to a dramatic score that is typical of the genre to find the right tone of the performance."
          ]
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/ko5JZe1bqtBnz/",
      "summary": "If you are going to “Break a Rule”...",
      "video": {
        "kind": "youtube",
        "videoId": "cJ1zhq3yNBM",
        "thirdParty": true,
        "note": "Third-party tutorial/reference embed preserved from the legacy course pages."
      }
    },
    {
      "slug": "example-dacre-stranger-things",
      "title": "Example: Dacre's Stranger Things Tape",
      "sectionSlug": "bending-the-rules",
      "body": [
        {
          "paragraphs": [
            "Dacre famously booked this Stranger Things Role by taking a chance."
          ]
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/ko5JZe1bqtBnz/",
      "summary": "Dacre famously booked this Stranger Things Role by taking a chance.",
      "video": {
        "kind": "missing",
        "legacyVimeoId": "336444157",
        "note": "Dacre Montgomery Stranger Things audition tape (third-party example). Vimeo is dead; decide on replacement or removal."
      },
      "needsReview": true,
      "reviewNote": "One or more videos in this lesson are unverified or awaiting a replacement."
    },
    {
      "slug": "example-nicholas-bw-tape",
      "title": "Example: Nicholas' Black & White Tape",
      "sectionSlug": "bending-the-rules",
      "body": [
        {
          "heading": "Casting does not want your filmmaker interpretation of the sides. / But what if adding a fitting touch to the scene could really give it the proper tone and enhance the performance.",
          "paragraphs": [
            "What if it promised to be enjoyable too?"
          ]
        }
      ],
      "resources": [],
      "legacyAdobeUrl": "https://express.adobe.com/page/ko5JZe1bqtBnz/",
      "summary": "What if it promised to be enjoyable too?",
      "video": {
        "kind": "missing",
        "legacyVimeoId": "395384847",
        "note": "Nicholas' black-and-white self tape example (client example).",
        "candidates": [
          "46fa375d-1ba0-4692-a857-bf128af53bfa - Nicholas Young - Scared.mp4 (main library)"
        ]
      },
      "needsReview": true,
      "reviewNote": "One or more videos in this lesson are unverified or awaiting a replacement."
    }
  ]
};
